apiVersion: v1
appVersion: v1.18.0
description: Cinder CSI Plugin for OpenStack
name: cinder-csi-chart
version: 1.2.0
home: https://github.com/kubernetes/cloud-provider-openstack
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
  - name: brtknr
    email: brtknr@bath.edu
