apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: cephfs-mount
            mountPath: /srv
            subPath: bharat
        securityContext:
          runAsUser: 2024
          allowPrivilegeEscalation: true
      volumes:
        - name: cephfs-mount
          persistentVolumeClaim:
            claimName: manila-cephfs-pvc
            readOnly: false
